- name: 1.1 Ensure a separate partition for containers has been created (Scored)\
  debug: msg="This is a manual configuration"
  tags:
   - not_scored
   - section1.2

- name: 1.2 Ensure the container host has been Hardened (Not Scored)
  debug: msg="Not covered by this role"
  tags:
   - not_scored
   - section1.2

- name: 1.3 Ensure Docker is up to date (Not Scored)
  yum:
    name: docker-ce
    state: latest
  tags:
   - not_scored
   - section1.3

- name: 1.4 Ensure only trusted users are allowed to control Docker daemon (Scored)
  user:
    name: "{{ item }}"
    group: docker 
  with_items: "{{ tursted_users }}"
  tags:
   - scored
   - section1.4

- name: 1.5 Ensure auditing is configured for the docker daemon (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.5

- name: 1.6 Ensure auditing is configured for Docker files and directories - /var/lib/docker (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /var/lib/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.6


- name: 1.7 Ensure auditing is configured for Docker files and directories - /etc/docker (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /etc/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.7

- name: 1.8 Ensure auditing is configured for Docker files and directories - docker.service (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/lib/systemd/system/docker.service -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.8

- name: 1.9 Ensure auditing is configured for Docker files and directories - docker.socket (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/lib/systemd/system/docker.socket -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.9

- name: 1.10 Ensure auditing is configured for Docker files and directories - /etc/default/docker (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /etc/default/docker -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.10

- name: 1.11 Ensure auditing is configured for Docker files and directories - /etc/docker/daemon.json (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /etc/docker/daemon.json -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.11

- name: 1.12 Ensure auditing is configured for Docker files and directories - /usr/bin/docker-containerd (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/docker-containerd -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.12

- name: 1.13 Ensure auditing is configured for Docker files and directories - /usr/bin/docker-runc (Scored)
  lineinfile: 
    dest: /etc/audit/rules.d/audit.rules 
    line: "-w /usr/bin/docker-runc -k docker"
    state: present
  notify: Reload auditd Rules
  tags:
   - scored
   - section1.13